name: build
on: workflow_call
jobs:

  nfpm:
    runs-on: ubuntu-latest
    needs: installcheck
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Create pg_restore_points DEB 17 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_17.yaml --packager deb
      - name: Create pg_restore_points RPM 17 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_17.yaml --packager rpm
      - name: Create pg_restore_points DEB 16 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_16.yaml --packager deb
      - name: Create pg_restore_points RPM 16 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_16.yaml --packager rpm
      - name: Create pg_restore_points DEB 15 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_15.yaml --packager deb
      - name: Create pg_restore_points RPM 15 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_15.yaml --packager rpm
      - name: Create pg_restore_points DEB 14 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_14.yaml --packager deb
      - name: Create pg_restore_points RPM 14 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_14.yaml --packager rpm
      - name: Create pg_restore_points DEB 13 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_13.yaml --packager deb
      - name: Create pg_restore_points RPM 13 Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config=./nfpm/pg_restore_points_13.yaml --packager rpm

      - name: Archive pg_restore_points Package
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            *_amd64.deb
            *.x86_64.rpm
          retention-days: 1